/*
Payments Direct API

Testing IdentitiesV3APIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package paymentsdirect

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/paymentsdirect"
)

func Test_paymentsdirect_IdentitiesV3APIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IdentitiesV3APIService CreateFinancialInstrument", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var identityId string

		resp, httpRes, err := apiClient.IdentitiesV3API.CreateFinancialInstrument(context.Background(), identityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentitiesV3APIService CreateIdentity", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdentitiesV3API.CreateIdentity(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentitiesV3APIService DeactivateFinancialInstrumentV3", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var identityId string
		var financialInstrumentId string

		httpRes, err := apiClient.IdentitiesV3API.DeactivateFinancialInstrumentV3(context.Background(), identityId, financialInstrumentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentitiesV3APIService DeactivateIdentityV3", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var identityId string

		httpRes, err := apiClient.IdentitiesV3API.DeactivateIdentityV3(context.Background(), identityId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentitiesV3APIService GetFinancialInstrumentById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var identityId string
		var financialInstrumentId string

		resp, httpRes, err := apiClient.IdentitiesV3API.GetFinancialInstrumentById(context.Background(), identityId, financialInstrumentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentitiesV3APIService GetFinancialInstruments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var identityId string

		resp, httpRes, err := apiClient.IdentitiesV3API.GetFinancialInstruments(context.Background(), identityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentitiesV3APIService GetIdentities", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdentitiesV3API.GetIdentities(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentitiesV3APIService GetIdentityById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var identityId string

		resp, httpRes, err := apiClient.IdentitiesV3API.GetIdentityById(context.Background(), identityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentitiesV3APIService PutFinancialInstrument", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var identityId string
		var financialInstrumentId string

		resp, httpRes, err := apiClient.IdentitiesV3API.PutFinancialInstrument(context.Background(), identityId, financialInstrumentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdentitiesV3APIService PutIdentity", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var identityId string

		resp, httpRes, err := apiClient.IdentitiesV3API.PutIdentity(context.Background(), identityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
